version: '3'

networks:
  default:
    driver: bridge

services:
  filetransferservice:
    restart: always
    image: golang:1.18-alpine
    ports:
        - "8080:8080"
    networks:
        - default
    volumes:
        - "./:/home/app"
    command:
      - sh
      - -c
      - |
        cd /home/app
        go mod download
        go mod verify
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .
        ls -lah
        ./main
    environment:
        API_URL: https://procedure-sandbox.prozorro.sale
        API_URL_DGF: https://dgf-procedure-sandbox.prozorro.sale
