FROM golang:1.18-alpine
WORKDIR /app
COPY . .

ENV MYSQLUSER $MYSQLUSER
ENV MYSQLPASS $MYSQLPASS
ENV MYSQLDOMEN $MYSQLDOMEN
ENV MYSQLDBNAME $MYSQLDBNAME

RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .

CMD ["./main"]
